system:
  autostop:
    enabled: true
    timeout: 2

inputs:
  - type: tail
    path: examples/example.log
    tag: LOG

outputs:
  - type: stdout

rules:
  - tag: EXAMPLE_UUID
    transform:
      - type: uuid
        target: my_super_id
